### ISSUE TITLE
IsAlt() method returns false positives

### ISSUE THREAD

**Issue by straup** [whosonfirst/go-whosonfirst-geojson-v2#4]
It's time to revisit the `IsAlt()` logic for `whosonfirst` properties since it is causing things like Asia to be reported as an alt file.

https://github.com/whosonfirst/go-whosonfirst-geojson-v2/blob/master/properties/whosonfirst/whosonfirst.go#L276-L283

https://spelunker.whosonfirst.org/id/102191569/

**Comment by thisisaaronland** [comment]
Should be fixed as of `0.11.0` release.
