### ISSUE TITLE
Update IsAlt test to include src:alt_label  and ditch wof:parent_id test

### ISSUE THREAD

**Issue by stepps00** [whosonfirst/go-whosonfirst-geojson-v2#6]
https://github.com/whosonfirst/go-whosonfirst-geojson-v2/blob/master/properties/whosonfirst/whosonfirst.go#L288-L295

This seems to incorrectly flags "default" WOF records as alt files (`is_alt` = 1) in some cases. As the comment mentions, this logic should check a Who's On First record for the "wof:parent_id" property, and if not present, flag the record as an alt file.

Once https://github.com/whosonfirst-data/whosonfirst-data/issues/1714 lands, this check should be obsolete, so I'm going to suggest we ditch this check and purely rely on the property additions to the alt files themselves to flag a file as an alt.

**Comment by nvkelso** [comment]
Per comment in https://github.com/whosonfirst-data/whosonfirst-data/issues/1714, we should also add test for `src:alt_label` as equivalent to `wof:alt_label` when calculating IsAlt.
